title: Farzana Anjum Esha
description: Data Scientist | ML Researcher | Fraud Detection
theme: minima

# Pages for header navigation
header_pages:
  - index.md
  - projects.md
  - research.md
  - blog.md

# Custom CSS
sass:
  style: assets/css/style.scss
